### ISSUE TITLE
Crash with admob on android

### ISSUE THREAD

**Issue by ramsestom** [fbricker/extension-multiads#1]
Trying to use the extension on android with admod ads.
The application crash with this error message:

E/AndroidRuntime(29577): FATAL EXCEPTION: main
E/AndroidRuntime(29577): java.lang.NoClassDefFoundError: android.support.v4.util.SimpleArrayMap
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.zzq.<init>(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.zzq.<init>(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.zzb.<init>(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.zzc.<init>(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.zzf.<init>(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.client.zzz.zzdb(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.client.zzz.zzda(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.internal.client.zzz.zza(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source)
E/AndroidRuntime(29577):        at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
E/AndroidRuntime(29577):        at admobex.AdMobEx.reloadBanner(AdMobEx.java:243)
E/AndroidRuntime(29577):        at admobex.AdMobEx.reinitBanner(AdMobEx.java:226)
E/AndroidRuntime(29577):        at admobex.AdMobEx.<init>(AdMobEx.java:163)
E/AndroidRuntime(29577):        at admobex.AdMobEx.getInstance(AdMobEx.java:57)
E/AndroidRuntime(29577):        at admobex.AdMobEx$1.run(AdMobEx.java:73)
E/AndroidRuntime(29577):        at android.os.Handler.handleCallback(Handler.java:632)
E/AndroidRuntime(29577):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(29577):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(29577):        at android.app.ActivityThread.main(ActivityThread.java:4777)
E/AndroidRuntime(29577):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(29577):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(29577):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(29577):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(29577):        at dalvik.system.NativeStart.main(Native Method)

**Comment by fbricker** [comment]
Hi, if you just need to use AdMob, you should use extension-admob directly.
This extension is made to use multiple ad networks on the same app (including some mediation options), but it relays on other extensions to display ads.

About this issue, please check that you have the last version of Google Play Services lib installed from your android device manager.

If this does not solves your case, then please open an issue directly here: https://github.com/openfl/extension-admob (including Lime + OpenFL version and specify if you're using lime next or lime legacy).

Thanks!
